In [143]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split

In [144]:
#mason df is declared to the cleaned dataset from the midterm
df = pd.read_csv('cleaned_hotel_bookings.csv')

In [145]:
#mason check initial size before split
df.head(1)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,month,total_guests,stay_duration,is_family,arrival_date,arrival_month_num,is_weekend_arrival
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Check-Out,00:00.0,1,2,0,0,7/1/2015,7,0

In [146]:
#mason split dataset into 70 train/30 temp
train_df, temp_df = train_test_split(df, test_size=0.3, random_state=42)

In [147]:
#mason splitting temp_df into validation_df and test_df so its 15/15
validation_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

In [148]:
#mason checking sizes of each new split (in order of train,validation,test)
print("-- Size of New features created --")
print()
print()
print("Train set:", len(train_df))
print()
print("Validation set:", len(validation_df))
print()
print("Test set:", len(test_df))

-- Size of New features created --


Train set: 83573

Validation set: 17908

Test set: 17909

In [149]:
#mason download the splits to .csv format for later use
train_df.to_csv("train.csv", index=False)
validation_df.to_csv("val.csv", index=False)
test_df.to_csv("test.csv", index=False)

In [150]:
#mason confirmed downloaded files
!ls -1

cleaned_hotel_bookings.csv
sample_data
test.csv
train.csv
val.csv

In [151]:
#mason checking size, ensuring its the cleaned dataset
df.shape
df.head(8)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,month,total_guests,stay_duration,is_family,arrival_date,arrival_month_num,is_weekend_arrival
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Check-Out,00:00.0,1,2,0,0,7/1/2015,7,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Check-Out,00:00.0,1,2,0,0,7/1/2015,7,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Check-Out,00:00.0,1,1,1,0,7/1/2015,7,0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Check-Out,00:00.0,1,1,1,0,7/1/2015,7,0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,1,Check-Out,00:00.0,1,2,2,0,7/1/2015,7,0
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,1,Check-Out,00:00.0,1,2,2,0,7/1/2015,7,0
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,0,Check-Out,00:00.0,1,2,2,0,7/1/2015,7,0
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,1,Check-Out,00:00.0,1,2,2,0,7/1/2015,7,0

In [152]:
# -----------##########   LINEAR REGRESSION or LOGISTIC REGRESSION  ##########################################--------------

In [153]:
#mason                      #################       use train.csv not cleaned_hotel_bookings.csv

In [154]:
train_df = pd.read_csv('train.csv')